import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { api } from '../services/api';

export default function FacultyAssignmentSubmissions() {
  const { assignmentId }=useParams(); const navigate=useNavigate(); const [submissions,setSubmissions]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [processing,setProcessing]=useState(null); const [drafts,setDrafts]=useState({});
  async function load(){try{setLoading(true);setError('');const data=await api.getGradingSubmissions(assignmentId);setSubmissions(Array.isArray(data)?data:[]);setDrafts((prev)=>{const next={...prev};(Array.isArray(data)?data:[]).forEach(s=>{if(!next[s.id])next[s.id]={marksObtained:s.marks_obtained??'',feedback:s.feedback??''}});return next})}catch(e){setError(e.message||'Failed to load submissions')}finally{setLoading(false)}}
  useEffect(()=>{if(assignmentId)load()},[assignmentId]);
  function setDraft(id,key,value){setDrafts((d)=>({...d,[id]:{...(d[id]||{}),[key]:value}}))}
  async function grade(id){try{setProcessing(id);setError('');await api.gradeAssignmentSubmission(id,drafts[id]||{});await load()}catch(e){setError(e.message||'Unable to grade submission')}finally{setProcessing(null)}}
  async function approve(id){try{setProcessing(id);await api.approveAssignmentSubmission(id);await load()}catch(e){setError(e.message||'Unable to approve')}finally{setProcessing(null)}}
  async function reject(id){try{setProcessing(id);await api.rejectAssignmentSubmission(id);await load()}catch(e){setError(e.message||'Unable to reject')}finally{setProcessing(null)}}
  if(loading)return <div className="panel">Loading submissions...</div>;
  return <div><div className="ledger-heading"><div><h2>Assignment submissions</h2><p style={{margin:'6px 0 0',color:'var(--muted-text)'}}>Review files, approve/reject submissions, and record marks and feedback.</p></div><span className="count">{submissions.length} submissions</span></div><hr className="ledger-rule"/>
    {error&&<div className="panel"><div className="error-text">{error}</div></div>}
    <div className="panel">{submissions.length===0?<p>No students have submitted this assignment yet.</p>:<div style={{display:'grid',gap:14}}>{submissions.map(s=>{const d=drafts[s.id]||{};return <div key={s.id} style={{border:'1px solid var(--rule)',padding:14,borderRadius:'var(--radius)'}}><div className="ledger-heading"><div><h3>{s.student_name}</h3><span className="code-stamp">{s.student_code}</span> <span style={{color:'var(--muted-text)',fontSize:12}}>{s.email}</span></div><span className={s.status==='rejected'?'pill pill-bad':s.status==='pending'?'pill pill-warn':'pill pill-good'}>{s.status}</span></div><p style={{fontSize:12,color:'var(--muted-text)'}}>Submitted: {s.submitted_at?new Date(s.submitted_at).toLocaleString('en-IN'):'-'}</p><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:12}}>{s.file_path&&<a className="btn btn-outline" href={api.getFileUrl(s.file_path)} target="_blank" rel="noreferrer">Open submission</a>}{s.status==='pending'&&<><button className="btn" onClick={()=>approve(s.id)} disabled={processing===s.id}>{processing===s.id?'Processing...':'Approve'}</button><button className="btn btn-outline" onClick={()=>reject(s.id)} disabled={processing===s.id}>Reject</button></>}</div><div className="card-grid"><label style={{display:'grid',gap:6,fontSize:12,fontWeight:700}}>Marks (out of 100)<input className="input" type="number" min="0" max="100" step="0.5" value={d.marksObtained} onChange={(e)=>setDraft(s.id,'marksObtained',e.target.value)} /></label><label style={{display:'grid',gap:6,fontSize:12,fontWeight:700}}>Feedback<textarea className="input" rows="3" value={d.feedback} onChange={(e)=>setDraft(s.id,'feedback',e.target.value)} placeholder="Feedback for the student" /></label></div><button className="btn" style={{marginTop:10}} onClick={()=>grade(s.id)} disabled={processing===s.id}>{processing===s.id?'Saving...':'Save grade & feedback'}</button>{s.marks_obtained!==null&&<div style={{marginTop:8,fontSize:12,color:'var(--muted-text)'}}>Current grade: <strong>{s.marks_obtained}/100</strong>{s.feedback?` — ${s.feedback}`:''}</div>}</div>})}</div>}</div>
    <div className="panel"><button className="btn btn-outline" onClick={()=>navigate('/faculty/assignments')}>← Back to assignments</button></div>
  </div>;
}
