import { useEffect, useMemo, useState } from 'react';
import { api } from '../services/api';

const EXAM_TYPES = ['CT1', 'CT2', 'INTERNAL', 'EXTERNAL', 'END SEMESTER'];
const API_ORIGIN = (import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/api').replace(/\/api\/?$/, '');
const examLabel = (examType) => String(examType || '').trim().toUpperCase() || '-';

export default function Marksheet() {
  const [marks,setMarks]=useState([]); const [marksheets,setMarksheets]=useState([]); const [metrics,setMetrics]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [downloading,setDownloading]=useState(null);
  useEffect(()=>{(async()=>{try{const [marksData,marksheetData,metricData]=await Promise.all([api.getMarks(),api.getMarksheet(),api.getAcademicMetrics()]);setMarks(marksData||[]);setMarksheets(marksheetData||[]);setMetrics(metricData||null);}catch(e){setError(e.message||'Unable to load marks.')}finally{setLoading(false)}})()},[]);
  const normalizedMarks=useMemo(()=>marks.map((m)=>({...m,exam_type:examLabel(m.exam_type)})),[marks]);
  const subjectRows=useMemo(()=>{const grouped={};normalizedMarks.forEach((m)=>{const key=m.code||m.subject;if(!grouped[key])grouped[key]={subject:m.subject,code:m.code,marks:{}};grouped[key].marks[m.exam_type]=m});return Object.values(grouped)},[normalizedMarks]);
  const percentage=(m)=>!m||!Number(m.max_marks)?'-':`${((Number(m.obtained_marks)/Number(m.max_marks))*100).toFixed(1)}%`;
  async function downloadMarksheet(sheet){if(!sheet.file_path)return;try{setDownloading(sheet.id);const r=await fetch(`${API_ORIGIN}${sheet.file_path}`);if(!r.ok)throw new Error('Unable to download marksheet');const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=sheet.file_name||`marksheet-semester-${sheet.semester_number}.pdf`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch(e){setError(e.message||'Unable to download marksheet')}finally{setDownloading(null)}}
  if(loading)return <div className="panel">Loading marks...</div>;
  return <div>
    <div className="ledger-heading"><div><h2>Marksheet & Marks</h2><p style={{margin:'6px 0 0',color:'var(--muted-text)'}}>Published examination marks, calculated academic performance and official marksheets.</p></div><span className="count">Published</span></div><hr className="ledger-rule" />
    {error&&<div className="panel"><div className="error-text">{error}</div></div>}
    <div className="panel"><div className="ledger-heading"><div><h2>Calculated Academic Performance</h2><p style={{margin:'6px 0 0',color:'var(--muted-text)'}}>Automatically calculated from published marks and subject credits. Final exam marks are preferred when available.</p></div><span className="count">CGPA {metrics?.currentCgpa ?? '—'}</span></div>
      {!metrics?.semesters?.length?<p>No published marks are available for SGPA/CGPA calculation yet.</p>:<div className="table-wrapper"><table className="ledger-table"><thead><tr><th>Semester</th><th>SGPA</th><th>CGPA</th><th>Credits</th><th>Subjects used</th></tr></thead><tbody>{metrics.semesters.map(s=><tr key={s.semesterId}><td>Semester {s.semesterNumber}</td><td><strong>{s.sgpa}</strong></td><td><strong>{s.cgpa}</strong></td><td>{s.totalCredits}</td><td>{s.subjects.length}</td></tr>)}</tbody></table></div>}
    </div>
    <div className="panel"><div className="ledger-heading"><h2>Subject-wise Marks</h2><span className="count">{normalizedMarks.length} entries</span></div>{subjectRows.length===0?<p>No published marks available.</p>:<div className="table-wrapper"><table className="ledger-table"><thead><tr><th>Subject</th><th>Code</th>{EXAM_TYPES.map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{subjectRows.map(row=><tr key={row.code||row.subject}><td>{row.subject}</td><td><span className="code-stamp">{row.code}</span></td>{EXAM_TYPES.map(t=>{const m=row.marks[t];return <td key={t}>{m?<div><strong>{m.obtained_marks}/{m.max_marks}</strong><br/><small>{m.grade||'-'} · {percentage(m)}</small></div>:'-'}</td>})}</tr>)}</tbody></table></div>}</div>
    {EXAM_TYPES.map(t=>{const rows=normalizedMarks.filter(m=>m.exam_type===t);return <div className="panel" key={t}><div className="ledger-heading"><h2>{t} Marks</h2><span className="count">{rows.length} subjects</span></div>{rows.length===0?<p>No published {t} marks available.</p>:<div className="table-wrapper"><table className="ledger-table"><thead><tr><th>Subject</th><th>Code</th><th>Marks</th><th>Percentage</th><th>Grade</th></tr></thead><tbody>{rows.map((m,i)=><tr key={`${t}-${m.code}-${i}`}><td>{m.subject}</td><td><span className="code-stamp">{m.code}</span></td><td>{m.obtained_marks}/{m.max_marks}</td><td>{percentage(m)}</td><td>{m.grade||'-'}</td></tr>)}</tbody></table></div>}</div>})}
    <div className="panel"><div className="ledger-heading"><div><h2>Published Marksheets</h2><p style={{margin:'6px 0 0',color:'var(--muted-text)'}}>Official PDF marksheets uploaded and published by faculty.</p></div><span className="count">{marksheets.length} document{marksheets.length===1?'':'s'}</span></div>{marksheets.length===0?<p>No published marksheet available yet.</p>:<div className="table-wrapper"><table className="ledger-table"><thead><tr><th>Semester</th><th>SGPA</th><th>CGPA</th><th>Result</th><th>Published</th><th>Document</th></tr></thead><tbody>{marksheets.map((sheet,i)=><tr key={sheet.id||i}><td>Semester {sheet.semester_number}</td><td>{sheet.sgpa??'-'}</td><td>{sheet.cgpa??'-'}</td><td>{sheet.result_status||'-'}</td><td><span className="pill pill-good">Published</span></td><td><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><a className="btn btn-outline" href={`${API_ORIGIN}${sheet.file_path}`} target="_blank" rel="noreferrer">View PDF</a><button className="btn" onClick={()=>downloadMarksheet(sheet)} disabled={downloading===sheet.id}>{downloading===sheet.id?'Downloading...':'Download'}</button></div><small style={{display:'block',marginTop:6,color:'var(--muted-text)'}}>{sheet.file_name}</small></td></tr>)}</tbody></table></div>}</div>
  </div>;
}
