import { useEffect, useState } from 'react';
import { api } from '../services/api';

export default function StudentSuccess() {
  const [state, setState] = useState({ loading: true, data: null });
  useEffect(() => { Promise.allSettled([api.getAttendance(), api.getAcademicMetrics(), api.getAssignments()]).then(([a,m,as]) => { const attendance = a.status === 'fulfilled' ? a.value : {}; const metrics = m.status === 'fulfilled' ? m.value : {}; const assignments = as.status === 'fulfilled' ? as.value : []; const list = Array.isArray(assignments) ? assignments : assignments.assignments || []; const pct = Number(attendance.overallPercentage ?? attendance.overall_percentage ?? 0); const cgpa = Number(metrics.cgpa ?? metrics.CGPA ?? metrics.currentCgpa ?? 0); const pending = list.filter(x => !['submitted','graded','completed'].includes(String(x.status || '').toLowerCase())).length; const score = Math.max(0, Math.min(100, Math.round(pct * .55 + Math.min(cgpa / 10, 1) * 30 + Math.max(0, 15 - pending * 3)))); setState({ loading: false, data: { pct, cgpa, pending, score } }); }); }, []);
  if (state.loading) return <div className="panel">Loading success score...</div>;
  const { pct, cgpa, pending, score } = state.data;
  const risk = score < 55 || pct < 75;
  return <div className="page-shell"><div className="page-heading"><div><span className="dashboard-kicker">Student success</span><h1>Success Score</h1><p>A simple snapshot of the signals that influence your academic progress.</p></div></div><div className="card-grid"><section className="panel success-score-card"><span className="dashboard-kicker">Current score</span><strong>{score}<small>/100</small></strong><div className="progress-track"><span style={{ width: `${score}%` }} /></div><b>{risk ? 'Needs attention' : 'On track'}</b></section><section className="panel"><h2>Why this score?</h2><div className="success-grid"><div><span>Attendance</span><strong>{pct}%</strong></div><div><span>CGPA</span><strong>{cgpa || '—'}</strong></div><div><span>Pending work</span><strong>{pending}</strong></div></div></section></div><section className="panel"><h2>Early warning</h2><p>{risk ? 'Your current signals suggest that a little focused effort could improve your academic position.' : 'Your current signals look healthy. Keep your attendance and coursework consistent.'}</p>{pct < 75 && <div className="notice warning">Attendance is below the 75% target. Prioritize upcoming classes.</div>}{pending > 2 && <div className="notice warning">You have {pending} active assignments. Consider clearing the oldest first.</div>}{!risk && <div className="notice success">No major warning signal detected from the available data.</div>}</section></div>;
}
