const express=require('express');
const router=express.Router();
const authenticate=require('../middleware/auth');
const authorize=require('../middleware/roleCheck');
const controller=require('../controllers/notificationController');
router.use(authenticate,authorize('student','faculty','admin'));
router.get('/',controller.listNotifications);
router.patch('/:id/read',controller.markRead);
router.post('/read-all',controller.markAllRead);
module.exports=router;
