const pool=require('../config/db');

async function getStudentId(userId){const r=await pool.query('SELECT id FROM students WHERE user_id=$1',[userId]);return r.rows[0]?.id||null}
async function getFacultyId(userId){const r=await pool.query('SELECT id FROM faculty WHERE user_id=$1',[userId]);return r.rows[0]?.id||null}

async function studentAnalytics(req,res,next){try{const studentId=await getStudentId(req.user.id);if(!studentId)return res.status(404).json({error:'Student profile not found'});const [attendance,marks,assignments,achievements]=await Promise.all([
pool.query(`SELECT s.code,s.name,COUNT(a.id)::int total,COUNT(a.id) FILTER(WHERE a.status='present')::int present FROM student_subjects ss JOIN subjects s ON s.id=ss.subject_id AND (ss.status IS NULL OR ss.status='approved') LEFT JOIN attendance a ON a.student_id=ss.student_id AND a.subject_id=ss.subject_id WHERE ss.student_id=$1 GROUP BY s.id,s.code,s.name ORDER BY s.code`,[studentId]),
pool.query(`SELECT s.code,s.name,s.credits,m.exam_type,m.obtained_marks,m.max_marks,m.created_at FROM marks m JOIN subjects s ON s.id=m.subject_id JOIN student_subjects ss ON ss.student_id=m.student_id AND ss.subject_id=m.subject_id AND (ss.status IS NULL OR ss.status='approved') WHERE m.student_id=$1 AND m.published=true ORDER BY m.created_at DESC,m.id DESC`,[studentId]),
pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE sub.id IS NOT NULL)::int submitted,COUNT(*) FILTER(WHERE sub.status='pending')::int pending,COUNT(*) FILTER(WHERE sub.status='rejected')::int rejected,COUNT(*) FILTER(WHERE sub.id IS NULL)::int not_submitted FROM assignments a JOIN student_subjects ss ON ss.student_id=$1 AND ss.subject_id=a.subject_id AND (ss.status IS NULL OR ss.status='approved') LEFT JOIN assignment_submissions sub ON sub.assignment_id=a.id AND sub.student_id=$1`,[studentId]),
pool.query(`SELECT COUNT(*)::int count FROM achievements WHERE student_id=$1`,[studentId])]);const a=attendance.rows.map(x=>({...x,percentage:x.total?Number((x.present*100/x.total).toFixed(2)):0}));const t=a.reduce((n,x)=>n+x.total,0),p=a.reduce((n,x)=>n+x.present,0);const latest=new Map();for(const m of marks.rows)if(!latest.has(m.code))latest.set(m.code,m);const perf=[...latest.values()].map(m=>({...m,percentage:Number((Number(m.max_marks)?Number(m.obtained_marks)*100/Number(m.max_marks):0).toFixed(2))}));const avg=perf.length?Number((perf.reduce((n,x)=>n+x.percentage,0)/perf.length).toFixed(2)):0;res.json({attendance:a,overallAttendance:t?Number((p*100/t).toFixed(2)):0,performance:perf,averagePublishedMarks:avg,assignmentSummary:assignments.rows[0],achievements:achievements.rows[0]?.count||0,generatedAt:new Date().toISOString()})}catch(e){next(e)}}

async function facultyAnalytics(req,res,next){try{const facultyId=await getFacultyId(req.user.id);if(!facultyId)return res.status(404).json({error:'Faculty profile not found'});const [subjects,submissions,marks,materials]=await Promise.all([
pool.query(`SELECT s.id,s.code,s.name,COUNT(DISTINCT ss.student_id)::int students FROM faculty_subject_assignments fsa JOIN subjects s ON s.id=fsa.subject_id LEFT JOIN student_subjects ss ON ss.subject_id=s.id AND (ss.status IS NULL OR ss.status='approved') WHERE fsa.faculty_id=$1 GROUP BY s.id,s.code,s.name ORDER BY s.code`,[facultyId]),
pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE ass.status='pending')::int pending,COUNT(*) FILTER(WHERE ass.status='submitted')::int graded_or_submitted,COUNT(*) FILTER(WHERE ass.status='rejected')::int rejected FROM assignment_submissions ass JOIN assignments a ON a.id=ass.assignment_id JOIN faculty_subject_assignments fsa ON fsa.subject_id=a.subject_id AND fsa.faculty_id=$1`,[facultyId]),
pool.query(`SELECT COUNT(*)::int total,ROUND(AVG(CASE WHEN m.max_marks>0 THEN m.obtained_marks*100/m.max_marks END),2) average_percentage,COUNT(*) FILTER(WHERE m.published=true)::int published FROM marks m JOIN faculty_subject_assignments fsa ON fsa.subject_id=m.subject_id AND fsa.faculty_id=$1`,[facultyId]),
pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE sm.rag_status='indexed')::int indexed,COUNT(*) FILTER(WHERE sm.rag_status='failed')::int failed,COALESCE(SUM(sm.rag_chunks),0)::int chunks FROM study_materials sm JOIN faculty_subject_assignments fsa ON fsa.subject_id=sm.subject_id AND fsa.faculty_id=$1`,[facultyId])]);res.json({subjects:subjects.rows,submissions:submissions.rows[0],marks:marks.rows[0],materials:materials.rows[0],generatedAt:new Date().toISOString()})}catch(e){next(e)}}

async function adminAnalytics(req,res,next){try{const r=await pool.query(`SELECT (SELECT COUNT(*) FROM users WHERE role='student' AND is_active) active_students,(SELECT COUNT(*) FROM users WHERE role='faculty' AND is_active) active_faculty,(SELECT COUNT(*) FROM departments) departments,(SELECT COUNT(*) FROM courses) courses,(SELECT COUNT(*) FROM subjects) subjects,(SELECT COUNT(*) FROM assignments) assignments,(SELECT COUNT(*) FROM assignment_submissions) submissions,(SELECT COUNT(*) FROM assignment_submissions WHERE status='pending') pending_submissions,(SELECT COUNT(*) FROM notifications WHERE read_at IS NULL) unread_notifications,(SELECT COUNT(*) FROM study_materials WHERE rag_status='failed') rag_failed,(SELECT COALESCE(ROUND(AVG(CASE WHEN m.max_marks>0 THEN m.obtained_marks*100/m.max_marks END),2),0) FROM marks m WHERE m.published=true) average_published_marks,(SELECT COALESCE(ROUND(AVG(CASE WHEN x.total>0 THEN x.present*100.0/x.total END),2),0) FROM (SELECT student_id,subject_id,COUNT(*) total,COUNT(*) FILTER(WHERE status='present') present FROM attendance GROUP BY student_id,subject_id)x) average_attendance`);const recent=await pool.query(`SELECT al.action,al.entity,al.entity_id,al.created_at,u.full_name AS actor FROM audit_logs al LEFT JOIN users u ON u.id=al.user_id ORDER BY al.created_at DESC,al.id DESC LIMIT 20`);res.json({summary:r.rows[0],recentAudit:recent.rows,generatedAt:new Date().toISOString()})}catch(e){next(e)}}
module.exports={studentAnalytics,facultyAnalytics,adminAnalytics};