const pool=require('../config/db');
const DAY_NAMES=['','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
async function getStudent(){const r=await pool.query(`SELECT s.id,s.current_semester_id,s.division_id FROM students s WHERE s.user_id=$1`,[this]);return r.rows[0]||null}
async function listTimetable(req,res,next){try{let params=[];let where='';if(req.user.role==='student'){const r=await pool.query(`SELECT id,current_semester_id,division_id FROM students WHERE user_id=$1`,[req.user.id]);const st=r.rows[0];if(!st)return res.status(404).json({error:'Student profile not found'});params=[st.current_semester_id,st.division_id];where='WHERE te.semester_id=$1 AND (te.division_id IS NULL OR te.division_id=$2)';}else if(req.user.role==='faculty'){const r=await pool.query(`SELECT id FROM faculty WHERE user_id=$1`,[req.user.id]);const f=r.rows[0];if(!f)return res.status(404).json({error:'Faculty profile not found'});params=[f.id];where='WHERE te.faculty_id=$1';}else if(req.query.semesterId){params=[Number(req.query.semesterId),req.query.divisionId?Number(req.query.divisionId):null];where='WHERE te.semester_id=$1 AND ($2::integer IS NULL OR te.division_id=$2)';}
const r=await pool.query(`SELECT te.id,te.semester_id,te.division_id,te.subject_id,te.faculty_id,te.day_of_week,${DAY_NAMES.map((n,i)=>i?`'${n}'`:'NULL').slice(1).join(',')} AS _unused,TO_CHAR(te.start_time,'HH24:MI') AS start_time,TO_CHAR(te.end_time,'HH24:MI') AS end_time,te.room,te.class_type,te.notes,s.name AS subject,s.code AS subject_code,u.full_name AS faculty_name,sem.number AS semester_number,d.name AS division_name FROM timetable_entries te JOIN subjects s ON s.id=te.subject_id LEFT JOIN faculty f ON f.id=te.faculty_id LEFT JOIN users u ON u.id=f.user_id JOIN semesters sem ON sem.id=te.semester_id LEFT JOIN divisions d ON d.id=te.division_id ${where} ORDER BY te.day_of_week,te.start_time`,params);res.json(r.rows.map(x=>{const{_unused,...rest}=x;return{...rest,day_name:DAY_NAMES[Number(x.day_of_week)]}}));}catch(e){next(e)}}
async function createTimetable(req,res,next){try{const{semesterId,divisionId,subjectId,facultyId,dayOfWeek,startTime,endTime,room,classType,notes}=req.body;if(!semesterId||!subjectId||!dayOfWeek||!startTime||!endTime)return res.status(400).json({error:'semesterId, subjectId, dayOfWeek, startTime and endTime are required'});const r=await pool.query(`INSERT INTO timetable_entries(semester_id,division_id,subject_id,faculty_id,day_of_week,start_time,end_time,room,class_type,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id`,[semesterId,divisionId||null,subjectId,facultyId||null,dayOfWeek,startTime,endTime,room||null,classType||'Lecture',notes||null]);res.status(201).json({message:'Timetable entry created',id:r.rows[0].id});}catch(e){next(e)}}
async function updateTimetable(req,res,next){try{const id=Number(req.params.id);const{semesterId,divisionId,subjectId,facultyId,dayOfWeek,startTime,endTime,room,classType,notes}=req.body;const r=await pool.query(`UPDATE timetable_entries SET semester_id=$1,division_id=$2,subject_id=$3,faculty_id=$4,day_of_week=$5,start_time=$6,end_time=$7,room=$8,class_type=$9,notes=$10 WHERE id=$11 RETURNING id`,[semesterId,divisionId||null,subjectId,facultyId||null,dayOfWeek,startTime,endTime,room||null,classType||'Lecture',notes||null,id]);if(!r.rows.length)return res.status(404).json({error:'Timetable entry not found'});res.json({message:'Timetable entry updated'});}catch(e){next(e)}}
async function deleteTimetable(req,res,next){try{const id=Number(req.params.id);const r=await pool.query('DELETE FROM timetable_entries WHERE id=$1 RETURNING id',[id]);if(!r.rows.length)return res.status(404).json({error:'Timetable entry not found'});res.json({message:'Timetable entry deleted'});}catch(e){next(e)}}
module.exports={listTimetable,createTimetable,updateTimetable,deleteTimetable};
